Adding more repositories descriptions & alphabetical sorting
PrestaShop/core-weekly-generator pull request #26
Opened 2020-03-17 09:32 UTC by ttoine

I sorted the list of repositories (keeping categories), so it will be more easy to add new ones or fix an existing one.

2020-03-17 09:35 UTC, eternoendless approved these changes
LGTM

2020-03-17 09:37 UTC, ttoine commented on coreteam.py
> +    'statsregistrations': 'Registrations statistics modules'
```suggestion
    'statsregistrations': 'Registrations statistics modules',
```

2020-03-17 09:42 UTC, ttoine commented
I tested my small fix locally, it is working. thanks @PierreRambaud for noticing.

2020-03-18 10:26 UTC, Progi1984 commented on coreteam.py
> +     'ps_emailsubscription': 'Email subscription module',
```suggestion
    'ps_emailsubscription': 'Email subscription module',
```

2020-03-18 10:27 UTC, Progi1984 commented on coreteam.py
> +    'traces': 'Traces',
TopContributors ?

2020-03-18 10:39 UTC, ttoine commented on coreteam.py
> +    'traces': 'Traces',
What do you think about that?
```suggestion
    'traces': 'Traces',
    'TopContributors': 'PrestaShop contributors website"
```

2020-03-18 10:57 UTC, Progi1984 commented on coreteam.py
> +    'traces': 'Traces',
ok for me

2020-03-18 11:14 UTC, Progi1984 approved these changes

2020-03-18 13:22 UTC, PierreRambaud commented on coreteam.py
> +    'TopContributors': 'PrestaShop contributors website"
```suggestion
    'TopContributors': 'PrestaShop contributors website',
```

2020-03-18 13:22 UTC, PierreRambaud requested changes
Typo

2020-03-18 13:35 UTC, PierreRambaud approved these changes

2020-03-18 13:35 UTC, merged

2020-03-18 13:35 UTC, PierreRambaud commented
Thanks @ttoine